services:
  - type: web
    name: dywy
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    healthCheckPath: /backoffice/index.html
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: APP_AUTH_ADMIN_EMAILS
        sync: false
      - key: APP_AUTH_READ_ONLY_EMAILS
        sync: false
      - key: APP_AUTH_SUCCESS_REDIRECT_URL
        sync: false
      - key: APP_GUEST_ACCESS_BASE_URL
        sync: false
      - key: APP_GUEST_AREA_URL
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
        sync: false
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
        sync: false
      - key: APP_DEEZER_ACCESS_TOKEN
        sync: false
      - key: APP_DEEZER_PLAYLIST_ID
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_PORT
        sync: false
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: SERVER_FORWARD_HEADERS_STRATEGY
        value: framework
